import "bootstrap/dist/css/bootstrap.css";
import "../styles/featured-courses.css";
import "../styles/services.css";
import "../styles/header.css";
import "../styles/banner.css";
import "../styles/main.css";
import "../styles/responsiveness.css";

import "swiper/css";
import "swiper/css/navigation";
import "./globals.css";

import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import BootstrapClient from "@/providers/bootstrapClient";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--poppins-font",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        {children}
        {/* add boostrapClient to app, this will run only in client */}
        <BootstrapClient />
      </body>
    </html>
  );
}
